project_id = "bbvaaiawykjgjyxvlmqx"

[functions.chat]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.evaluate-session]
verify_jwt = false

[functions.matchmaking]
verify_jwt = false

[functions.evaluate-peer-session]
verify_jwt = false
